version: '3.8'

services:
  app:
    image: phuoc20207/cloud_basic_sql
    command: >
      sh -c "export SQL_ENDPOINT=sql_endpoint && export SQL_USER=sql_user && export SQL_PASSWORD=sql_password && uvicorn app:app --host 0.0.0.0 --port 80"
    ports:
      - "3000:80"
    expose:
      - 3000
 
